### PR TITLE
Add SDJ Community

### PR DESCRIPTION
**Pull request by Vrq**
Our organization also supports the Berlin Code of Conduct (we are a hub that connects Swiss tech communities)

### CODE REVIEW

**Comment by hagenburger** [comment]
@Vrq is SwissDevJobs hosting/organizing all those events? Do you speak for all of them and apply the COC to each one?

**Comment by Vrq** [comment]
@hagenburger we can only speak on our behalf (& the events that we organize) + we can also suggest the Berlin COC to those communities.

**Review by hagenburger — CHANGES_REQUESTED** [review]
@Vrq the aim of the Berlin Code of Conduct is to create a safe space for people joining events. If it might indicate an event is run under the BCOC but at the end is not, it might not be a safe space.

Therefore I suggest you explicitly add each of those events you can make the attendees aware of the BCOC in the beginning and enforce the rules when needed yourself. Would you be fine with that?

If you further advocate the BCOC to other events, that is a great offer and thank for for doing so!

**Comment by Vrq** [comment]
@Vrq I think we misunderstood each other a bit :)

I am adding explicitly our community (which is in the same time a Hub of Swiss communities) and this means that we (SwissDevJobs) enforce the rules of BCOC at OUR events and our own community.

**Comment by hagenburger** [comment]
@Vrq please see my comment above. The link you provided – https​://swissdevjobs.ch/community – is, seen from an outside perspective, a list of links to events on a commercial website. It is not clear what “our community” is and which events you speak for and which not. Those questions must be clear to create a safe space for attendees. The BCOC is made to protect attendees, it’s not made for lists.

**Comment by Vrq** [comment]
@hagenburger, all right - I changed the link to point to our main page to make it more clear.

**Comment by hagenburger** [comment]
This is a commercial website not an event. I still did not get an answer which events you organize and speak for.

With all the respect for the start-up you built – which is great –, BCOC is made for attendees, it’s not made to support commercial projects.

**Pull request closed without merging**
