### PR TITLE
adding School of MA to code of conduct

### PR DESCRIPTION
**Pull request by schoolofma**
thanks:)

### CODE REVIEW

**Comment by skade** [comment]
Cool, I never heard of @schoolofma and this looks interesting.

Welcome and congratulations to PR 42!

**Comment by schoolofma** [comment]
yay, wonderful, thank you!

On Fri, Feb 27, 2015 at 1:04 PM, Florian Gilcher <notifications@github.com>
wrote:

> Cool, I never heard of @schoolofma <https://github.com/schoolofma> and
> this looks interesting.
>
> Welcome and congratulations to PR 42!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rubyberlin/code-of-conduct/pull/42#issuecomment-76384851>
> .
>



-- 
*School of Machines, Making & Make-Believe*
http://schoolofma.org/

**Comment by schoolofma** [comment]
hi Florian,

out of curiosity, is there any chance to add 'Schools' to the title of that
page which
currently reads User groups and conferences? I know for example
OpenTechSchool
are considering joining the list after we properly run through our approval
process.

would be wonderful! let me know, thanks:)

cheers,
Rachel



On Fri, Feb 27, 2015 at 1:06 PM, Rachel Uwa <info@schoolofma.org> wrote:

> yay, wonderful, thank you!
>
> On Fri, Feb 27, 2015 at 1:04 PM, Florian Gilcher <notifications@github.com
> > wrote:
>
>> Cool, I never heard of @schoolofma <https://github.com/schoolofma> and
>> this looks interesting.
>>
>> Welcome and congratulations to PR 42!
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/rubyberlin/code-of-conduct/pull/42#issuecomment-76384851>
>> .
>>
>
>
>
> --
> *School of Machines, Making & Make-Believe*
> http://schoolofma.org/
>
>


-- 
*School of Machines, Making & Make-Believe*
http://schoolofma.org/

**Comment by schoolofma** [comment]
or perhaps "organisations"--  more broad, but still relevant !

On Fri, Feb 27, 2015 at 1:08 PM, Rachel Uwa <info@schoolofma.org> wrote:

> hi Florian,
>
> out of curiosity, is there any chance to add 'Schools' to the title of
> that page which
> currently reads User groups and conferences? I know for example
> OpenTechSchool
> are considering joining the list after we properly run through our
> approval process.
>
> would be wonderful! let me know, thanks:)
>
> cheers,
> Rachel
>
>
>
> On Fri, Feb 27, 2015 at 1:06 PM, Rachel Uwa <info@schoolofma.org> wrote:
>
>> yay, wonderful, thank you!
>>
>> On Fri, Feb 27, 2015 at 1:04 PM, Florian Gilcher <
>> notifications@github.com> wrote:
>>
>>> Cool, I never heard of @schoolofma <https://github.com/schoolofma> and
>>> this looks interesting.
>>>
>>> Welcome and congratulations to PR 42!
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/rubyberlin/code-of-conduct/pull/42#issuecomment-76384851>
>>> .
>>>
>>
>>
>>
>> --
>> *School of Machines, Making & Make-Believe*
>> http://schoolofma.org/
>>
>>
>
>
> --
> *School of Machines, Making & Make-Believe*
> http://schoolofma.org/
>
>


-- 
*School of Machines, Making & Make-Believe*
http://schoolofma.org/

**Comment by skade** [comment]
I'll file a ticket, but I don't see any issue there. I think it is a good idea.

Display-wise, we don't group them anyways at the moment, but we probably should start then.

**Pull request merged**
