### PR TITLE
Add contacts to React Day Berlin section

### PR DESCRIPTION
**Pull request by operatino**

### CODE REVIEW

**Comment by operatino** [comment]
There's both brand contact, and my personal, anything else to be added?

**Comment by skade** [comment]
We usually recommend against brand contacts, as they don't give a good feeling for who's behind it. A specific email address, like "coc-team@..." or "grievances@..." is better, as other emails are generally quite liberally given access to.

**Comment by operatino** [comment]
If there's both the name of the main organizer (me), and the team mailbox, there's still a personal connection + an alternative option. I have quite a lot of email coming in, so shared mailbox would output a lot higher chance for rapid response. But I'm open for your suggestions. "coc-team@" email could be an option, but in our case it will target same people as "hi@".

Fair to note, that on-site (during conference) we'll have a team of organizers, that would be ready to help with any occasion, and direct contact would be the most efficient. 

Let me know what's the best option, and we'll implement it.

**Comment by operatino** [comment]
Hey everyone,

Any more comments on the change? We get requests for contacts update.

**Comment by skade** [comment]
Hi, sorry, I missed the notification here. I would still suggest a "coc-team@"-shared mailbox with a constrained set of recipients there. 

In any case, I'll merge it, if you change anything there, please post another pull request.

**Pull request merged**
