### PR TITLE
Statement addressing the display of inappropriate content

### LINKED ISSUE #40: Display of violence
We had an incident today, which still saddens me and I'm sorry about. :'(

The incident was about a display of brutal violence against animals. This was triggering to an attendee and others found it to be inappropriate as well.

I'm for adding this to the code of conduct, that such pictures are unwelcome. It can be tricky to formulate.

I'm happy to hear about ideas, input, whatever.

We have to figure out and implement #39 before we can move along with this.

Tobi

### PR DESCRIPTION
**Pull request by PragTob**
This is an attempt to resolve #40 

I'm looking for feedback - it's rather wordy and maybe at times my English isn't the best. I tried to condense a lot of content from #40 into this and make it more general than "just" violence. Not quite sure if this sits in the right spot in the coc either.

Please let me know how you feel about this and suggest improvements or alternative solutions. Or just tell me you'd rather roll with #45 if that's the case. This is aimed to be more general while also more explicit about some things that were discussed.

### CODE REVIEW

**Comment by PragTob** [comment]
I might also have gotten to explicit in what I wrote here, please advise everyone :)

**Comment by PragTob** [comment]
Hi everyone,

so right now I don't know why there hasn't been input here so far either:

* Nobody had time so far
* this suggestion is that bad that no one wants to say why/how
* people say we should just go with what @rentalcustard suggested
* this suggestion is good enough and people just want to get it over with

No idea, but I'd appreciate a bit of feedback therefore I'm gonna ping some people

@skade @thilo @hagenburger @rentalcustar @xamebax @chastell @eljojo

**Comment by eljojo** [comment]
After reading both several times I find @rentalcustard's (#45) better. I like that it's much simpler.

**Comment by skade** [comment]
I'm unsure, but I tend towards #45. I agree with @rentalcustard's opinion in another thread to avoid being too instructional. If you want to inform speakers, an email beforehand should suffice.

**Comment by chastell** [comment]
I also slightly lean towards #45 as both simpler and more universal.

**Comment by PragTob** [comment]
Everyone seemed to be more happy with Tom's version, closing out

**Pull request closed without merging**
