### PR TITLE
Improve Russian translation

### PR DESCRIPTION
**Pull request by ave2me**
I am very excited about CoC being finally translated to Russian. So I suggest a few improvements to Russian localization.

### CODE REVIEW

**Comment by nazarov-tech** [comment]
@ave2me the changes are valid

However your commit message is not quite good, rewrite it please. It should be imperative and it should mention the Russian translation.

**Comment by nazarov-tech** [comment]
also rewrite merge request title in the same way

**Comment by nazarov-tech** [comment]
@hagenburger I approve this PR now, could you merge?

**Comment by hagenburger** [comment]
Done. Deployment to follow tonight.

**Pull request merged**
