### PR TITLE
Include statement addressing violent imagery

### PR DESCRIPTION
**Pull request by rentalcustard**
Following #40, here's a draft amendment to the CoC. I'm very happy to take suggestions on the wording or where it should appear in the document. Specifically, I'm not sure that it's strictly **harassment**, as opposed to 'unacceptable behaviour', but it seemed to fit more naturally with the list of examples after "harassment includes" than after "unacceptable behaviours include".

### CODE REVIEW

**Comment by xamebax** [comment]
Thanks for opening this PR! It looks fine by me. The wording is a bit specific: could it just be "violence", without specifying against whom ("violence" against things is actually just vandalism... right?)? I'm not going to argue though, I am not a native.

**Comment by chastell** [comment]
Should this kind of PRs wait till the changes are applied to non-English version? (I’m more than happy to update the Polish translation once the English verbiage is decided upon, just wondering in general.)

**Comment by rentalcustard** [comment]
@xamebax fair point. I've updated the wording, what do you think?

@chastell I was wondering the same thing. Could someone from @rubyberlin advise?

**Comment by xamebax** [comment]
@rentalcustard Neat!

**Comment by PragTob** [comment]
Hi all,
thanks for the suggestion!
#39 needs to be solved before this (or any significant changes) can really get in. Sorry :(

The question about changes is to be addressed in #39 as well. My current idea would be to make a new branch until it is ready to become new master... or something like that.

Tobi

**Comment by eljojo** [comment]
I think the keyword **inappropriate** solves [Florian's point](https://github.com/rubyberlin/code-of-conduct/issues/40#issuecomment-77543444) very well.
The question is: when is it appropriate?

What about something along the lines of:

### A note on depictions of Violence
In some cases, depictions of violence in public spaces (including slides) might be inappropriate. If you're interested in showing depictions of violence, please ask the organisers first.

does it sound like too much? cc @rentalcustard @skade

**Comment by rentalcustard** [comment]
We don't include similar qualifications for the sexual imagery exclusion we
already have. I also feel like the word 'inappropriate' gives plenty of
leeway to organisers.

**Comment by skade** [comment]
You are right there. I still follow the notion that CoCs are a baseline anyways and organisers discretion is always a thing.

**Comment by eljojo** [comment]
I might be taking the discussion to a different level, but my point is, if we have to define it in the code of conduct (and if we need a code of conduct) is because certain things are not obvious.
If we use the word appropriate, it assumes that the attendee already knows what's appropriate for most people and what's not.

Of course, this are just my 2 cents :)

**Comment by skade** [comment]
Hi, I'd like to put this on the fast track. If there are no comments on this up to tonight, I'll vote for merging.

We should resolve this at least before rug-b, two month of time is an edge for me.

**Comment by PragTob** [comment]
totally with you there, also want to get this in before next week. I'll put in some time this evening before my project group - basically what I'd try is a version that is more general but references the display of violence and other unwanted content (similiar to what was suggested in the thread).

I'm not available for discussions during the day, though.

**Comment by chastell** [comment]
Is the English wording decided? If so, should we add the translations to this PR?

**Comment by PragTob** [comment]
No wording is not decided yet, sorry. I didn't have time yesterday evening (project group + rug::b organization) I'll try to have something up this evening.

**Comment by PragTob** [comment]
(and so evening becomes night)

I wrote up another proposal in #54 - please let me know what you think. I tired to make it more generally applicable (not "just" the display of violence) and include other thigns such as necessary trigger warnings if somehow this is the main content of a talk.

**Comment by skade** [comment]
I'd like to bump this.

**Comment by PragTob** [comment]
I'll try to get this done this weekend, I'll most likely merge tom's PR as I believe that is what everyone was most happy with.

**Comment by skade** [comment]
\o/

**Comment by PragTob** [comment]
Hey,

so similar changes are included in #63 at the same place, what we have here is:

> inappropriate use of nudity and/or sexual images in public spaces (including presentation slides); inappropriate depictions of violence in public spaces (including presentation slides); 

vs.

> inappropriate use of nudity, violent and/or sexual imagery;

(the part of presentations was pulled up a bit over there)

The changes are rather similar, the one in #63 is more succinct so I'd favor it. Then again, my favor for things was already against popular opinion couple of times :)

**Comment by rentalcustard** [comment]
I'm fine with #63 and would like to avoid another prolonged discussion before finally getting some form of change in.

**Comment by skade** [comment]
Hm, can we bring either #63 or this one to a close? I appreciate the effort to make all corners better, but this has been waiting for months and we promised fast movement.

**Comment by lauralindal** [comment]
Maybe some explanation why we pulled the presentation slide part up in #63 : It seemed to make more sense as there was already a "list" of where this unacceptable behavior could take place (online, etc). Whereas if it stayed in the second (current) paragraph, it would logically appear as if unacceptable behavior other than harrasing (so e.g. intimidation, derogatory speech etc) would be okay on presentation slides. I'm pretty sure that is not what we mean :)

**Comment by rentalcustard** [comment]
@lauralindal that makes sense to me!

**Comment by skade** [comment]
Merged and sorry for taking that long. We're going to amend it in a following PR, addressing "in public spaces", which we feel like introducing more confusion then clarification.

**Pull request merged**
