### PR TITLE
Add Berlin C++ User Group

### PR DESCRIPTION
**Pull request by FabioFracassi**
We want to use the CoC. please add us to your list.

### CODE REVIEW

**Comment by skade** [comment]
Hello and welcome! 👍

**Comment by FabioFracassi** [comment]
Any idea when the website will be reflecting the change?

**Comment by skade** [comment]
@FabioFracassi Sorry, there was a problem hitting the button. :) (Also, the JSON was broken)

**Comment by FabioFracassi** [comment]
It works now, ... sorry about the json, thanks for fixing.

**Pull request merged**
