### PR TITLE
Add license statement

### PR DESCRIPTION
**Pull request by PragTob**
Includes German and English version.

Missing: Spani/Polish also a review

### CODE REVIEW

**Comment by PragTob** [comment]
@chastell @xamebax @eljojo @myabc could you please edit/add the corresponding versions in your respective language? Thanks <3

**Comment by chastell** [comment]
Done, apologies for taking so much time. I also fixed some rogue Unicode characters in the English version.

BTW: Was there a conscious decision to use American English for the _licence_? ;)

**Comment by skade** [comment]
I don't think so and we usually standardise on spelling.

**Comment by PragTob** [comment]
Thanks Piotr!

There wasn't - I think it's just our American influenced culture. I won't
have an AE and BE version though, that's just confusing.

sent from my mobile - sorry for the brevity

www.pragtob.info

**Comment by chastell** [comment]
Ok, thanks for the info. The rest of the CoC is in AmE, so let’s keep ‘license’ for this PR and come back to the Serious Issue of Spellink separately when there are no more pressing issues. :)

**Comment by PragTob** [comment]
@eljojo @myabc some Spanish would be highly appreciated :)

**Comment by eljojo** [comment]
@PragTob just updated the Spanish version. Maybe @catalanojuan could also share his opinion, but I think it's ok. (at least good enough).

**Comment by eljojo** [comment]
I guess this is ready to merge :shipit:

**Comment by catalanojuan** [comment]
lgtm! Thanks for looping me in!

**Comment by PragTob** [comment]
now I just notice that we are missing our brand new french version... @lucaspinto @fannivuniconnu @gregkare @thegcat

**Comment by lucaspinto** [comment]
I slept on this, sorry. I'll be taking care of it during Easter.

**Comment by PragTob** [comment]
Thanks lucas :)

**Comment by opensourcegrrrl** [comment]
@PragTob Nice work! I assume the license will be international. :) http://creativecommons.org/licenses/by-sa/4.0/

**Comment by PragTob** [comment]
@lucaspinto @fannivuniconnu @gregkare @thegcat A small french version would be highly appreciated so we can merge this in :)

**Comment by PragTob** [comment]
@opensourcegrrrl yes that is the license I'm referring to, maybe we should link to it

**Comment by thegcat** [comment]
@PragTob see #64

**Comment by thegcat** [comment]
@PragTob and regarding the license: I'd very much be in favor of linking to it with the corresponding locale, as I wouldn't have known where exactly to look either.

**Comment by PragTob** [comment]
first thanks, secondly we can probably work that in in the next revision :)

**Pull request merged**
