### PR TITLE
Use fonts with Cyrillic support

### PR DESCRIPTION
**Pull request by sapegin**
Feel free to suggest other fonts, or other implementation (like Google Fonts).

Before:

image 2018-10-17 at 9 54 06 am

After:

image 2018-10-17 at 9 53 31 am

### CODE REVIEW

**Comment by hagenburger** [comment]
Thanks, @sapegin, you were faster than me! I’ll have a look :)

**Comment by nazarov-tech** [comment]
I honestly can't see the difference on your screenshots.. the issue is valid though

**Comment by sapegin** [comment]
* Before: the browser has to fallback to Helvetica and Times New Roman.
* After: using Helvetica and Georgia for all languages.

**Comment by nazarov-tech** [comment]
@sapegin no no no

I understand both the technical difference and the value of your pull request

it's just I can't see the difference.. like, visually :(

(but what am I, just a coder)
(my world is ugly)

**Pull request closed without merging**
